version: '3'

services:
  db:
    container_name: BookGptDb
    image: postgres
    volumes:
      - postgres_data_new:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    container_name: backend
#    build: .
    image: docker.io/sahil7776/api
    command: make local-api
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  rqworker:
    container_name: rqworker
#    build: .
    image: docker.io/sahil7776/api
    command: python manage.py rqworker
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  postgres_data_new:
