version: '3'

services:
  db:
    container_name: design_stripe_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  rqworker:
    container_name: reworker
    build: .
    command: python manage.py rqworker
    volumes:
      - .:/code
    depends_on:
      - redis

volumes:
  postgres_data:
