openapi: 3.0.0
info:
  title: Design Stripe Book Gpt Parser API Project
  description: API documentation for Parser Project
  version: 1.0.0
servers:
  - url: http://localhost:8000/v1/

tags:
  - name: Parser
    description: |
      # Parsing Related Json API's

  - name: Chat
    description: |
      # Parsing Related Json API's
  - name: Prompt
    description: |
      # Prompt Related Json API's

paths:
  /parser/pdf:
    post:
      tags:
        - Parser
      summary: Parse PDF
      operationId: parsePdf
      requestBody:
        description: List of PDF URLs to parse and save to Langchain
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                urls:
                  type: array
                  items:
                    type: string
                    format: uri
                  example: [
                      "https://www.learnandmaster.com/resources/Learn-and-Master-Guitar-Lesson-Book.pdf",
                      "https://www.thisisclassicalguitar.com/wp-content/uploads/2021/03/Classical-Guitar-Method-Vol1-2020.pdf"
                    ]
              required:
                - urls
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "2 PDF parsing jobs queued"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_key:
                    type: array
                    items:
                      type: string
                      example: "Validation error"
        '500':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Something went wrong"
      security: [ ]
  /chat/:
    post:
      tags:
        - Chat
      summary: Get chat response on given prompt
      operationId: getChatResponse
      requestBody:
        description: Chat prompt
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
              required:
                - prompt
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      security: [ ]
  /prompts/:
    get:
      tags:
        - Prompt
      summary: Get list of all chat prompts
      operationId: getChatPrompts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: ["Hi, How are you","Heloo, what is your name"]
      security: [ ]
